"""
Unified Branch-Adaptive Interview Question Bank
Covers CSE, IT, ECE, EEE, Mechanical, Civil, Chemical, Aerospace
"""

QUESTION_BANK = {
    "CSE": {
        "roles": ["Software Engineer", "Data Scientist", "Full Stack Developer", "DevOps Engineer"],
        "Beginner": [
            {"id": "cse_b1", "question": "What is the difference between a stack and a queue?", "topic": "Data Structures"},
            {"id": "cse_b2", "question": "Explain what Object-Oriented Programming (OOP) means.", "topic": "OOP"},
            {"id": "cse_b3", "question": "What is an API and how does it work?", "topic": "Web Development"},
            {"id": "cse_b4", "question": "What is the difference between SQL and NoSQL databases?", "topic": "Databases"},
            {"id": "cse_b5", "question": "Explain the concept of recursion with an example.", "topic": "Algorithms"},
            {"id": "cse_b6", "question": "What is version control and why is Git important?", "topic": "Tools"},
            {"id": "cse_b7", "question": "What is an operating system and what are its main functions?", "topic": "OS"},
            {"id": "cse_b8", "question": "Explain the difference between HTTP and HTTPS.", "topic": "Networking"},
            {"id": "cse_b9", "question": "What is a linked list? When would you use it?", "topic": "Data Structures"},
            {"id": "cse_b10", "question": "What is the MVC design pattern?", "topic": "Software Design"},
            {"id": "cse_b11", "question": "What is time complexity and Big-O notation?", "topic": "Algorithms"},
            {"id": "cse_b12", "question": "What is the difference between a process and a thread?", "topic": "OS"},
        ],
        "Intermediate": [
            {"id": "cse_i1", "question": "Explain Dijkstra's shortest path algorithm.", "topic": "Algorithms"},
            {"id": "cse_i2", "question": "What are SOLID principles in software engineering?", "topic": "Software Design"},
            {"id": "cse_i3", "question": "Explain the CAP theorem in distributed systems.", "topic": "Distributed Systems"},
            {"id": "cse_i4", "question": "What is the difference between supervised and unsupervised learning?", "topic": "ML"},
            {"id": "cse_i5", "question": "How does a hash table work and what is a hash collision?", "topic": "Data Structures"},
            {"id": "cse_i6", "question": "Explain RESTful API design principles.", "topic": "Web Development"},
            {"id": "cse_i7", "question": "What are microservices and how do they differ from monolithic architecture?", "topic": "Architecture"},
            {"id": "cse_i8", "question": "Explain the concept of database normalization.", "topic": "Databases"},
            {"id": "cse_i9", "question": "What is Docker and why is containerization useful?", "topic": "DevOps"},
            {"id": "cse_i10", "question": "How does the TCP/IP model work?", "topic": "Networking"},
            {"id": "cse_i11", "question": "What is a binary search tree and how do you balance it?", "topic": "Data Structures"},
            {"id": "cse_i12", "question": "Explain dynamic programming with an example.", "topic": "Algorithms"},
        ],
        "Advanced": [
            {"id": "cse_a1", "question": "Design a URL shortening service like bit.ly.", "topic": "System Design"},
            {"id": "cse_a2", "question": "Explain the internals of garbage collection in Java/Python.", "topic": "Languages"},
            {"id": "cse_a3", "question": "How would you design a distributed caching system?", "topic": "System Design"},
            {"id": "cse_a4", "question": "Explain the difference between LSTM and Transformer models.", "topic": "Deep Learning"},
            {"id": "cse_a5", "question": "How does Kubernetes orchestrate containers?", "topic": "DevOps"},
            {"id": "cse_a6", "question": "Design a real-time chat system that supports millions of users.", "topic": "System Design"},
            {"id": "cse_a7", "question": "Explain consistent hashing in distributed systems.", "topic": "Distributed Systems"},
            {"id": "cse_a8", "question": "What is the two-phase commit protocol?", "topic": "Databases"},
        ],
    },
    "IT": {
        "roles": ["Software Developer", "Network Engineer", "IT Consultant", "Cloud Engineer"],
        "Beginner": [
            {"id": "it_b1", "question": "What is the difference between LAN and WAN?", "topic": "Networking"},
            {"id": "it_b2", "question": "Explain what cloud computing means.", "topic": "Cloud"},
            {"id": "it_b3", "question": "What is cybersecurity and why is it important?", "topic": "Security"},
            {"id": "it_b4", "question": "What is a firewall and how does it protect a network?", "topic": "Security"},
            {"id": "it_b5", "question": "Explain the client-server architecture.", "topic": "Architecture"},
            {"id": "it_b6", "question": "What is the OSI model?", "topic": "Networking"},
            {"id": "it_b7", "question": "What is virtualization in IT?", "topic": "Infrastructure"},
            {"id": "it_b8", "question": "Explain what DNS is and how it works.", "topic": "Networking"},
            {"id": "it_b9", "question": "What is DHCP and what problem does it solve?", "topic": "Networking"},
            {"id": "it_b10", "question": "What is the difference between symmetric and asymmetric encryption?", "topic": "Security"},
            {"id": "it_b11", "question": "What is an IP address and what are the different classes?", "topic": "Networking"},
            {"id": "it_b12", "question": "Explain the concept of subnetting.", "topic": "Networking"},
        ],
        "Intermediate": [
            {"id": "it_i1", "question": "Explain how SSL/TLS works during a HTTPS connection.", "topic": "Security"},
            {"id": "it_i2", "question": "What are the differences between AWS, Azure, and GCP?", "topic": "Cloud"},
            {"id": "it_i3", "question": "What is DevOps and what are its core practices?", "topic": "DevOps"},
            {"id": "it_i4", "question": "Explain the concept of Infrastructure as Code (IaC).", "topic": "DevOps"},
            {"id": "it_i5", "question": "What is a VPN and how does it provide security?", "topic": "Security"},
            {"id": "it_i6", "question": "Explain the OWASP Top 10 web security risks.", "topic": "Security"},
            {"id": "it_i7", "question": "What is load balancing and what are common algorithms?", "topic": "Infrastructure"},
            {"id": "it_i8", "question": "Explain the concept of CDN (Content Delivery Network).", "topic": "Networking"},
        ],
        "Advanced": [
            {"id": "it_a1", "question": "Design a highly available cloud infrastructure for a global application.", "topic": "Architecture"},
            {"id": "it_a2", "question": "How would you implement a zero-trust security model?", "topic": "Security"},
            {"id": "it_a3", "question": "Explain how BGP routing works on the internet.", "topic": "Networking"},
            {"id": "it_a4", "question": "How do you design a disaster recovery plan for an enterprise?", "topic": "Business Continuity"},
        ],
    },
    "ECE": {
        "roles": ["Embedded Engineer", "VLSI Engineer", "IoT Developer", "Signal Processing Engineer"],
        "Beginner": [
            {"id": "ece_b1", "question": "What is the difference between an analog and digital signal?", "topic": "Signals"},
            {"id": "ece_b2", "question": "Explain what a microcontroller is and how it differs from a microprocessor.", "topic": "Embedded Systems"},
            {"id": "ece_b3", "question": "What is Ohm's law? State its formula.", "topic": "Circuits"},
            {"id": "ece_b4", "question": "What is the difference between AM and FM modulation?", "topic": "Communication"},
            {"id": "ece_b5", "question": "Explain what a transistor is and its types.", "topic": "Electronics"},
            {"id": "ece_b6", "question": "What is I2C communication protocol?", "topic": "Protocols"},
            {"id": "ece_b7", "question": "Explain the concept of PWM (Pulse Width Modulation).", "topic": "Embedded Systems"},
            {"id": "ece_b8", "question": "What is CMOS technology?", "topic": "VLSI"},
            {"id": "ece_b9", "question": "What is a logic gate? Give examples.", "topic": "Digital Electronics"},
            {"id": "ece_b10", "question": "Explain Kirchhoff's Voltage and Current Laws.", "topic": "Circuits"},
            {"id": "ece_b11", "question": "What is the purpose of a PCB?", "topic": "Hardware"},
            {"id": "ece_b12", "question": "What is an ADC and a DAC?", "topic": "Embedded Systems"},
        ],
        "Intermediate": [
            {"id": "ece_i1", "question": "Explain the working of a PLL (Phase Locked Loop).", "topic": "Communication"},
            {"id": "ece_i2", "question": "What is UART communication and how does it work?", "topic": "Protocols"},
            {"id": "ece_i3", "question": "Explain the architecture of ARM Cortex-M processors.", "topic": "Embedded Systems"},
            {"id": "ece_i4", "question": "What is the difference between RISC and CISC architectures?", "topic": "Computer Architecture"},
            {"id": "ece_i5", "question": "Explain OFDM modulation used in 4G/5G.", "topic": "Communication"},
            {"id": "ece_i6", "question": "What is DMA (Direct Memory Access)?", "topic": "Embedded Systems"},
            {"id": "ece_i7", "question": "Explain the concept of real-time operating systems (RTOS).", "topic": "Embedded Systems"},
            {"id": "ece_i8", "question": "What are the trade-offs in VLSI design?", "topic": "VLSI"},
        ],
        "Advanced": [
            {"id": "ece_a1", "question": "Design an IoT-based smart home automation system.", "topic": "IoT"},
            {"id": "ece_a2", "question": "Explain 5G NR (New Radio) architecture.", "topic": "Communication"},
            {"id": "ece_a3", "question": "How do you optimize power consumption in embedded systems?", "topic": "Embedded Systems"},
            {"id": "ece_a4", "question": "Explain the working of a MIMO antenna system.", "topic": "Communication"},
        ],
    },
    "Mechanical": {
        "roles": ["Design Engineer", "Manufacturing Engineer", "Production Engineer", "Automotive Engineer"],
        "Beginner": [
            {"id": "me_b1", "question": "What is the difference between stress and strain?", "topic": "Mechanics"},
            {"id": "me_b2", "question": "Explain the first and second laws of thermodynamics.", "topic": "Thermodynamics"},
            {"id": "me_b3", "question": "What is the difference between static and kinetic friction?", "topic": "Mechanics"},
            {"id": "me_b4", "question": "What is CAD? Name common CAD software.", "topic": "Design"},
            {"id": "me_b5", "question": "Explain Young's Modulus and why it is important.", "topic": "Material Science"},
            {"id": "me_b6", "question": "What is a Gantt chart and how is it used in project management?", "topic": "Project Management"},
            {"id": "me_b7", "question": "What is GD&T (Geometric Dimensioning and Tolerancing)?", "topic": "Manufacturing"},
            {"id": "me_b8", "question": "Explain the working principle of a 4-stroke engine.", "topic": "Engines"},
            {"id": "me_b9", "question": "What is fatigue failure in materials?", "topic": "Material Science"},
            {"id": "me_b10", "question": "What is Bernoulli's equation and its applications?", "topic": "Fluid Mechanics"},
            {"id": "me_b11", "question": "Explain the difference between ductile and brittle materials.", "topic": "Material Science"},
            {"id": "me_b12", "question": "What is CNC machining?", "topic": "Manufacturing"},
        ],
        "Intermediate": [
            {"id": "me_i1", "question": "Explain Finite Element Analysis (FEA) and its applications.", "topic": "Analysis"},
            {"id": "me_i2", "question": "What is the difference between casting, forging, and machining?", "topic": "Manufacturing"},
            {"id": "me_i3", "question": "Explain the concept of heat treatment and its types.", "topic": "Material Science"},
            {"id": "me_i4", "question": "What is a PID controller and how is it used in mechanical systems?", "topic": "Control Systems"},
            {"id": "me_i5", "question": "Explain Mohr's circle and its use in stress analysis.", "topic": "Mechanics"},
            {"id": "me_i6", "question": "What is the difference between laminar and turbulent flow?", "topic": "Fluid Mechanics"},
            {"id": "me_i7", "question": "How does additive manufacturing (3D printing) work?", "topic": "Manufacturing"},
            {"id": "me_i8", "question": "Explain the concept of lean manufacturing.", "topic": "Manufacturing"},
        ],
        "Advanced": [
            {"id": "me_a1", "question": "Design a suspension system for a Formula SAE car.", "topic": "Design"},
            {"id": "me_a2", "question": "Explain composite material design for aerospace applications.", "topic": "Material Science"},
            {"id": "me_a3", "question": "How would you improve the efficiency of a gas turbine engine?", "topic": "Thermodynamics"},
            {"id": "me_a4", "question": "Explain topology optimization in structural design.", "topic": "Design"},
        ],
    },
    "Civil": {
        "roles": ["Structural Engineer", "Site Engineer", "Construction Manager", "Geotechnical Engineer"],
        "Beginner": [
            {"id": "cv_b1", "question": "What is the difference between tension and compression in structures?", "topic": "Structural"},
            {"id": "cv_b2", "question": "Explain the water-cement ratio and why it is important in concrete.", "topic": "Materials"},
            {"id": "cv_b3", "question": "What is a shear force and bending moment diagram?", "topic": "Structural"},
            {"id": "cv_b4", "question": "What are the types of foundations and when are they used?", "topic": "Geotechnical"},
            {"id": "cv_b5", "question": "Explain the concept of factor of safety.", "topic": "Structural"},
            {"id": "cv_b6", "question": "What are the properties of good concrete?", "topic": "Materials"},
            {"id": "cv_b7", "question": "What is AutoCAD used for in civil engineering?", "topic": "Tools"},
            {"id": "cv_b8", "question": "What is the difference between RCC and PCC?", "topic": "Materials"},
            {"id": "cv_b9", "question": "Explain the IS code for concrete mix design.", "topic": "Standards"},
            {"id": "cv_b10", "question": "What is soil liquefaction?", "topic": "Geotechnical"},
            {"id": "cv_b11", "question": "What is a critical path in project scheduling?", "topic": "Project Management"},
            {"id": "cv_b12", "question": "Explain the concept of Bar Bending Schedule (BBS).", "topic": "Construction"},
        ],
        "Intermediate": [
            {"id": "cv_i1", "question": "Explain the design of a simply supported beam under uniformly distributed load.", "topic": "Structural"},
            {"id": "cv_i2", "question": "What is retaining wall design and what parameters affect it?", "topic": "Geotechnical"},
            {"id": "cv_i3", "question": "Explain the concept of pre-stressed concrete.", "topic": "Structural"},
            {"id": "cv_i4", "question": "What is the significance of SPT (Standard Penetration Test)?", "topic": "Geotechnical"},
            {"id": "cv_i5", "question": "How do you design a water treatment plant?", "topic": "Environmental"},
            {"id": "cv_i6", "question": "Explain the use of BIM (Building Information Modeling).", "topic": "Tools"},
            {"id": "cv_i7", "question": "What is earthquake-resistant design?", "topic": "Structural"},
            {"id": "cv_i8", "question": "Explain the concept of effective stress in soil mechanics.", "topic": "Geotechnical"},
        ],
        "Advanced": [
            {"id": "cv_a1", "question": "Design a multi-story RCC building for a seismic zone.", "topic": "Structural"},
            {"id": "cv_a2", "question": "How do you manage a large infrastructure project with tight deadlines?", "topic": "Project Management"},
            {"id": "cv_a3", "question": "Explain the design of a cable-stayed bridge.", "topic": "Structural"},
            {"id": "cv_a4", "question": "What are smart city concepts in urban planning?", "topic": "Urban Planning"},
        ],
    },
    "EEE": {
        "roles": ["Electrical Engineer", "Power Systems Engineer", "Control Systems Engineer"],
        "Beginner": [
            {"id": "eee_b1", "question": "What is the difference between AC and DC current?", "topic": "Basics"},
            {"id": "eee_b2", "question": "Explain Faraday's law of electromagnetic induction.", "topic": "Electromagnetics"},
            {"id": "eee_b3", "question": "What is a transformer and how does it work?", "topic": "Machines"},
            {"id": "eee_b4", "question": "What is power factor and why is it important?", "topic": "Power Systems"},
            {"id": "eee_b5", "question": "What is the difference between active, reactive, and apparent power?", "topic": "Power Systems"},
            {"id": "eee_b6", "question": "Explain what a three-phase system is.", "topic": "Power Systems"},
            {"id": "eee_b7", "question": "What is a circuit breaker and how does it work?", "topic": "Protection"},
            {"id": "eee_b8", "question": "Explain the working of an induction motor.", "topic": "Machines"},
            {"id": "eee_b9", "question": "What is an inverter in power electronics?", "topic": "Power Electronics"},
            {"id": "eee_b10", "question": "Explain the concept of earthing/grounding in electrical systems.", "topic": "Safety"},
            {"id": "eee_b11", "question": "What is a relay and what is it used for?", "topic": "Protection"},
            {"id": "eee_b12", "question": "What is Lenz's law?", "topic": "Electromagnetics"},
        ],
        "Intermediate": [
            {"id": "eee_i1", "question": "Explain how a synchronous generator works in a power plant.", "topic": "Machines"},
            {"id": "eee_i2", "question": "What is SCADA and how is it used in power systems?", "topic": "Control"},
            {"id": "eee_i3", "question": "Explain load flow analysis in power systems.", "topic": "Power Systems"},
            {"id": "eee_i4", "question": "What is FACTS devices and how do they help power grids?", "topic": "Power Systems"},
            {"id": "eee_i5", "question": "Explain the working of a PID controller in electrical systems.", "topic": "Control"},
            {"id": "eee_i6", "question": "What is a Variable Frequency Drive (VFD)?", "topic": "Power Electronics"},
            {"id": "eee_i7", "question": "Explain the concept of renewable energy integration in the grid.", "topic": "Power Systems"},
            {"id": "eee_i8", "question": "What is the difference between protection coordination and selectivity?", "topic": "Protection"},
        ],
        "Advanced": [
            {"id": "eee_a1", "question": "Design a substation protection scheme for a 132kV grid.", "topic": "Protection"},
            {"id": "eee_a2", "question": "Explain smart grid architecture and its components.", "topic": "Smart Grid"},
            {"id": "eee_a3", "question": "How would you design a solar microgrid for a rural area?", "topic": "Renewables"},
            {"id": "eee_a4", "question": "Explain the challenges of integrating large-scale battery storage with the grid.", "topic": "Energy Storage"},
        ],
    },
    "Chemical": {
        "roles": ["Process Engineer", "Chemical Analyst", "Safety Engineer", "Petrochemical Engineer"],
        "Beginner": [
            {"id": "ch_b1", "question": "What is the difference between exothermic and endothermic reactions?", "topic": "Thermodynamics"},
            {"id": "ch_b2", "question": "Explain Le Chatelier's principle with an example.", "topic": "Equilibrium"},
            {"id": "ch_b3", "question": "What is mass transfer and where is it used?", "topic": "Transport Phenomena"},
            {"id": "ch_b4", "question": "Differentiate between batch and continuous reactors.", "topic": "Reaction Engineering"},
            {"id": "ch_b5", "question": "What is distillation and how does it work?", "topic": "Separation"},
            {"id": "ch_b6", "question": "Explain the heat exchanger and its types.", "topic": "Heat Transfer"},
            {"id": "ch_b7", "question": "What is Reynolds number and its significance?", "topic": "Fluid Dynamics"},
            {"id": "ch_b8", "question": "What are MSDS/SDS sheets?", "topic": "Safety"},
            {"id": "ch_b9", "question": "Explain Raoult's law.", "topic": "Thermodynamics"},
            {"id": "ch_b10", "question": "What is a P&ID diagram?", "topic": "Process Design"},
            {"id": "ch_b11", "question": "What is the difference between osmosis and reverse osmosis?", "topic": "Separation"},
            {"id": "ch_b12", "question": "What is catalysis and what are its types?", "topic": "Reaction Engineering"},
        ],
        "Intermediate": [
            {"id": "ch_i1", "question": "Explain the McCabe-Thiele method for distillation design.", "topic": "Separation"},
            {"id": "ch_i2", "question": "What is HAZOP analysis and why is it important?", "topic": "Safety"},
            {"id": "ch_i3", "question": "Explain the concept of residence time distribution in reactors.", "topic": "Reaction Engineering"},
            {"id": "ch_i4", "question": "What is a heat integration pinch analysis?", "topic": "Process Design"},
            {"id": "ch_i5", "question": "Explain catalytic cracking in petroleum refining.", "topic": "Petrochemicals"},
            {"id": "ch_i6", "question": "What is the LMTD method for heat exchanger design?", "topic": "Heat Transfer"},
            {"id": "ch_i7", "question": "Explain process simulation software like ASPEN Plus.", "topic": "Tools"},
            {"id": "ch_i8", "question": "What are the challenges in scaling up a chemical process?", "topic": "Scale-Up"},
        ],
        "Advanced": [
            {"id": "ch_a1", "question": "Design a complete ammonia synthesis plant with energy integration.", "topic": "Process Design"},
            {"id": "ch_a2", "question": "Discuss the challenges of CCS (Carbon Capture and Storage).", "topic": "Environment"},
            {"id": "ch_a3", "question": "How would you optimize a multi-stage reactor for maximum yield?", "topic": "Reaction Engineering"},
            {"id": "ch_a4", "question": "Explain the green chemistry principles and their industrial applications.", "topic": "Green Chemistry"},
        ],
    },
    "Aerospace": {
        "roles": ["Aerospace Engineer", "Structural Analyst", "Avionics Engineer", "Propulsion Engineer"],
        "Beginner": [
            {"id": "ae_b1", "question": "Explain the four forces acting on an aircraft in flight.", "topic": "Aerodynamics"},
            {"id": "ae_b2", "question": "What is Bernoulli's principle and how does it relate to lift?", "topic": "Aerodynamics"},
            {"id": "ae_b3", "question": "What is the difference between a turbojet and turbofan engine?", "topic": "Propulsion"},
            {"id": "ae_b4", "question": "Explain what Mach number is.", "topic": "Aerodynamics"},
            {"id": "ae_b5", "question": "What are composite materials and why are they used in aircraft?", "topic": "Materials"},
            {"id": "ae_b6", "question": "What is the role of avionics in modern aircraft?", "topic": "Avionics"},
            {"id": "ae_b7", "question": "Explain the concept of angle of attack and stall.", "topic": "Aerodynamics"},
            {"id": "ae_b8", "question": "What is orbital mechanics?", "topic": "Space"},
            {"id": "ae_b9", "question": "What is the difference between subsonic, transonic, and supersonic flight?", "topic": "Aerodynamics"},
            {"id": "ae_b10", "question": "Explain the principle of rocket propulsion.", "topic": "Propulsion"},
            {"id": "ae_b11", "question": "What is fly-by-wire technology?", "topic": "Control Systems"},
            {"id": "ae_b12", "question": "What is the significance of aspect ratio in wing design?", "topic": "Design"},
        ],
        "Intermediate": [
            {"id": "ae_i1", "question": "Explain the Finite Element Method used for aircraft structural analysis.", "topic": "Structural"},
            {"id": "ae_i2", "question": "What is aeroelasticity and what problems can it cause?", "topic": "Structural"},
            {"id": "ae_i3", "question": "Explain the working of a GPS-INS integrated navigation system.", "topic": "Navigation"},
            {"id": "ae_i4", "question": "What is the specific impulse of a rocket engine?", "topic": "Propulsion"},
            {"id": "ae_i5", "question": "Explain the design trade-offs in a supersonic aircraft.", "topic": "Design"},
            {"id": "ae_i6", "question": "What is computational fluid dynamics (CFD) used for in aerospace?", "topic": "CFD"},
            {"id": "ae_i7", "question": "Explain the working of a Ramjet engine.", "topic": "Propulsion"},
            {"id": "ae_i8", "question": "What is a thermal protection system for re-entry vehicles?", "topic": "Space"},
        ],
        "Advanced": [
            {"id": "ae_a1", "question": "Design a hypersonic vehicle thermal management system.", "topic": "Thermal"},
            {"id": "ae_a2", "question": "How would you design a satellite attitude control system?", "topic": "Space Systems"},
            {"id": "ae_a3", "question": "Explain all-electric aircraft challenges and future prospects.", "topic": "Propulsion"},
            {"id": "ae_a4", "question": "Describe the trade studies involved in selecting a launch vehicle architecture.", "topic": "Space"},
        ],
    },
}

# General aptitude/communication questions asked across all branches
COMMON_QUESTIONS = {
    "HR": [
        {"id": "hr1", "question": "Tell me about yourself.", "topic": "Introduction"},
        {"id": "hr2", "question": "Where do you see yourself in 5 years?", "topic": "Goals"},
        {"id": "hr3", "question": "What are your greatest strengths and weaknesses?", "topic": "Self-awareness"},
        {"id": "hr4", "question": "Describe a challenge you faced and how you overcame it.", "topic": "Problem Solving"},
        {"id": "hr5", "question": "Why do you want to work for this company?", "topic": "Motivation"},
        {"id": "hr6", "question": "How do you handle working under pressure?", "topic": "Stress Management"},
        {"id": "hr7", "question": "Are you a team player or prefer working alone? Why?", "topic": "Teamwork"},
        {"id": "hr8", "question": "What motivates you in your work?", "topic": "Motivation"},
    ]
}
